name: build-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Extract Project version
        id: project
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Build with Maven
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode --update-snapshots verify
      - name: Deploy package to repository
        if:  ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        env:
          REPOUSER: ${{ secrets.repouser }}
          REPOPASS: ${{ secrets.repopass }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>quinimbus-snapshots</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server><server><id>quinimbus-releases</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -DskipTests deploy

        